language: python
python:
  - 3.7
services:
    - docker
notifications:
    email:
        if: branch = master
        recipients:
            - franco.liberali@gmail.com
            - ejusto@fi.uba.ar
            - meiglesias@fi.uba.ar
            - lsportelli@fi.uba.ar
before_install:
    # instalar heroku CLI
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    # login to heroku registries
    - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
    - cd ..
    - git clone https://github.com/taller2fiuba/hello-world-acceptance-tests.git
    - git clone https://github.com/taller2fiuba/hello-world-node.git
    - sudo pip install --upgrade pip
install:
    # install deps
    - cd hello-world-acceptance-tests && sudo pip install -r requirements.txt
    - cd ../hello-world-flask && pip install -r app/requirements.txt
before_script:
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then
    ./bin/start-test-server;
    ../hello-world-node/bin/start-test-server;
    fi' # levantar las aplicaciones
script:
    - ./bin/exec-unit-tests.sh
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then
    cd ../hello-world-acceptance-tests;
    behave;
    fi'
after_script:
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then
    ../hello-world-flask/bin/stop-server;
    ../hello-world-node/bin/stop-server;
    fi'
after_success:
    - 'if [ "$TRAVIS_BRANCH" = "master" ]; then
    cd ../hello-world-flask;
    coveralls;
    docker build -t app .;
    docker tag app registry.heroku.com/$HEROKU_APP_NAME/web;
    fi'
deploy:
    provider: script
    script:
        # push to heroku
        docker push registry.heroku.com/$HEROKU_APP_NAME/web;
        heroku container:release web --app $HEROKU_APP_NAME
    on:
        branch: master
