language: python
python:
  - 3.8
services:
    - docker
notifications:
    email:
        if: branch = master
        recipients:
            - franco.liberali@gmail.com
            - ejusto@fi.uba.ar
            - meiglesias@fi.uba.ar
            - lsportelli@fi.uba.ar
install:
script:
    - '$TRAVIS_BUILD_DIR/bin/travis/run-unit-tests'
    - 'if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_PULL_REQUEST" = "true" ]; then
            $TRAVIS_BUILD_DIR/bin/travis/run-coveralls;       
            $TRAVIS_BUILD_DIR/bin/travis/run-acceptance-tests;
       fi'
deploy:
    provider: script
    script:
        $TRAVIS_BUILD_DIR/bin/travis/deploy-to-heroku
    on:
        branch: master
    
