version: '3'
services:
    dev:
        image: tiangolo/uwsgi-nginx-flask:python3.7
        volumes:
            - .:/var/www/app
        environment:
            STATIC_URL: "/static"
            STATIC_PATH: "/var/www/app/static"
            FLASK_APP: "app"
            FLASK_ENV: "development"
            PYTHONDONTWRITEBYTECODE: 1
        working_dir: /var/www/app
        command: bash bin/dev-bootstrap.sh
        ports:
            - 0.0.0.0:5000:5000

